id: Detonate File - Group-IB TDS Polygon
version: -1
name: Detonate File - Group-IB TDS Polygon
description: 'Detonate file using Group-IB TDS Polygon integration. This playbook
  returns relevant reports to the War Room and file reputations to the context data.
  The detonation supports the following file types: 7z, ace, ar, arj, bat, bz2, cab,
  chm, cmd, com, cpgz, cpl, csv, dat, doc, docm, docx, dot, dotm, dotx, eml, exe,
  gz, gzip, hta, htm, html, iqy, iso, jar, js, jse, lnk, lz, lzma, lzo,  lzh, mcl,
  mht, msg, msi, msp, odp, ods, odt, ots, ott, pdf, pif, potm, potx, pps, ppsm, ppsx,
  ppt, pptm, pptx, ps1, pub, py, pyc, r*, rar, reg, rtf, scr, settingcontent-ms, stc,
  svg, sxc, sxw, tar, taz,  .tb2, .tbz, .tbz2, tgz, tlz, txz, tzo, txt, url, uue,
  vbe, vbs, wsf, xar, xls, xlsb, xlsm, xlsx, xml, xz, z*, zip.'
starttaskid: "0"
tasks:
  "0":
    id: "0"
    taskid: 9501b3b5-5523-40bd-8af6-ae6a9d6ac607
    type: start
    task:
      id: 9501b3b5-5523-40bd-8af6-ae6a9d6ac607
      version: -1
      name: ""
      iscommand: false
      brand: ""
      description: ''
    nexttasks:
      '#none#':
      - "1"
    separatecontext: false
    view: |-
      {
        "position": {
          "x": 840,
          "y": 220
        }
      }
    note: false
    timertriggers: []
    ignoreworker: false
  "1":
    id: "1"
    taskid: fc02e787-ad1e-4381-8e8a-96bd716a9255
    type: regular
    task:
      id: fc02e787-ad1e-4381-8e8a-96bd716a9255
      version: -1
      name: polygon-upload-file
      description: Upload file for analysis
      script: Group-IB TDS Polygon|||polygon-upload-file
      type: regular
      iscommand: true
      brand: Group-IB TDS Polygon
    nexttasks:
      '#none#':
      - "11"
    scriptarguments:
      file_id:
        complex:
          root: inputs.file_id
      language:
        simple: en
      password: {}
    separatecontext: false
    view: |-
      {
        "position": {
          "x": 840,
          "y": 360
        }
      }
    note: false
    timertriggers: []
    ignoreworker: false
  "4":
    id: "4"
    taskid: 3515a2f8-6b03-4061-8125-756cc50294fd
    type: title
    task:
      id: 3515a2f8-6b03-4061-8125-756cc50294fd
      version: -1
      name: Done
      type: title
      iscommand: false
      brand: ""
      description: ''
    separatecontext: false
    view: |-
      {
        "position": {
          "x": 840,
          "y": 1580
        }
      }
    note: false
    timertriggers: []
    ignoreworker: false
  "11":
    id: "11"
    taskid: 70256af8-c846-4973-86a8-9c3361ee58b3
    type: playbook
    task:
      id: 70256af8-c846-4973-86a8-9c3361ee58b3
      version: -1
      name: GenericPolling
      description: |-
        Use this playbook as a sub-playbook to block execution of the master playbook until a remote action is complete.
        This playbook implements polling by continuously running the command in Step \#2 until the operation completes.
        The remote action should have the following structure:

        1. Initiate the operation.
        2. Poll to check if the operation completed.
        3. (optional) Get the results of the operation.
      playbookName: GenericPolling
      type: playbook
      iscommand: false
      brand: ""
    nexttasks:
      '#none#':
      - "14"
    scriptarguments:
      AdditionalPollingCommandArgNames: {}
      AdditionalPollingCommandArgValues: {}
      Ids:
        complex:
          root: Polygon
          accessor: Analysis.ID
          transformers:
          - operator: LastArrayElement
      Interval:
        simple: ${inputs.Interval}
      PollingCommandArgName:
        simple: tds_analysis_id
      PollingCommandName:
        simple: polygon-analysis-info
      Timeout:
        simple: ${inputs.Timeout}
      dt:
        simple: Polygon.Analysis(val.Status !== 'Finished').ID
    separatecontext: true
    loop:
      iscommand: false
      exitCondition: ""
      wait: 1
    view: |-
      {
        "position": {
          "x": 840,
          "y": 530
        }
      }
    note: false
    timertriggers: []
    ignoreworker: false
  "12":
    id: "12"
    taskid: 213cd7a1-88c6-4db7-823b-a83b9eb86041
    type: regular
    task:
      id: 213cd7a1-88c6-4db7-823b-a83b9eb86041
      version: -1
      name: polygon-report-export
      description: Download an archive with TDS Polygon report
      script: Group-IB TDS Polygon|||polygon-report-export
      type: regular
      iscommand: true
      brand: Group-IB TDS Polygon
    nexttasks:
      '#none#':
      - "17"
    scriptarguments:
      tds_analysis_id:
        complex:
          root: Polygon
          accessor: Analysis.ID
          transformers:
          - operator: LastArrayElement
      tds_file_id:
        complex:
          root: Polygon
          accessor: Analysis.ID
          transformers:
          - operator: LastArrayElement
    separatecontext: false
    view: |-
      {
        "position": {
          "x": 840,
          "y": 870
        }
      }
    note: false
    timertriggers: []
    ignoreworker: false
  "14":
    id: "14"
    taskid: 4a79b7e8-4212-4b47-8078-bfb2dde6e1b4
    type: regular
    task:
      id: 4a79b7e8-4212-4b47-8078-bfb2dde6e1b4
      version: -1
      name: polygon-analysis-info
      description: Get TDS Polygon analysis information
      script: Group-IB TDS Polygon|||polygon-analysis-info
      type: regular
      iscommand: true
      brand: Group-IB TDS Polygon
    nexttasks:
      '#none#':
      - "12"
    scriptarguments:
      tds_analysis_id:
        complex:
          root: Polygon
          accessor: Analysis.ID
          transformers:
          - operator: LastArrayElement
      tds_file_id:
        complex:
          root: Polygon
          accessor: Analysis.ID
          transformers:
          - operator: LastArrayElement
    separatecontext: false
    view: |-
      {
        "position": {
          "x": 840,
          "y": 700
        }
      }
    note: false
    timertriggers: []
    ignoreworker: false
  "15":
    id: "15"
    taskid: 51267f81-b57d-441f-8d0e-1bc50c8719f5
    type: condition
    task:
      id: 51267f81-b57d-441f-8d0e-1bc50c8719f5
      version: -1
      name: Does network activity dump exist?
      description: Check if a given value is true. Will return 'no' otherwise
      type: condition
      iscommand: false
      brand: ""
    nexttasks:
      '#default#':
      - "4"
      "yes":
      - "16"
    separatecontext: false
    conditions:
    - label: "yes"
      condition:
      - - operator: isTrue
          left:
            value:
              complex:
                root: Polygon
                accessor: Analysis.DumpExists
                transformers:
                - operator: LastArrayElement
            iscontext: true
    view: |-
      {
        "position": {
          "x": 840,
          "y": 1220
        }
      }
    note: false
    timertriggers: []
    ignoreworker: false
  "16":
    id: "16"
    taskid: 0305eaf1-0d73-4eb6-85a0-e1f2fdc1f7a4
    type: regular
    task:
      id: 0305eaf1-0d73-4eb6-85a0-e1f2fdc1f7a4
      version: -1
      name: polygon-pcap-export
      description: Network activity dump export
      script: Group-IB TDS Polygon|||polygon-pcap-export
      type: regular
      iscommand: true
      brand: Group-IB TDS Polygon
    nexttasks:
      '#none#':
      - "4"
    scriptarguments:
      tds_analysis_id:
        complex:
          root: Polygon
          accessor: Analysis.ID
          transformers:
          - operator: LastArrayElement
      tds_file_id:
        complex:
          root: Polygon
          accessor: File.ID
          transformers:
          - operator: LastArrayElement
    separatecontext: false
    view: |-
      {
        "position": {
          "x": 1210,
          "y": 1410
        }
      }
    note: false
    timertriggers: []
    ignoreworker: false
  "17":
    id: "17"
    taskid: 85900554-7d31-40c5-8f59-d212f2942abd
    type: regular
    task:
      id: 85900554-7d31-40c5-8f59-d212f2942abd
      version: -1
      name: polygon-video-export
      description: Screen activity video export
      script: Group-IB TDS Polygon|||polygon-video-export
      type: regular
      iscommand: true
      brand: Group-IB TDS Polygon
    nexttasks:
      '#none#':
      - "15"
    scriptarguments:
      tds_analysis_id:
        complex:
          root: Polygon
          accessor: Analysis.ID
          transformers:
          - operator: LastArrayElement
    separatecontext: false
    view: |-
      {
        "position": {
          "x": 840,
          "y": 1045
        }
      }
    note: false
    timertriggers: []
    ignoreworker: false
view: |-
  {
    "linkLabelsPosition": {
      "15_16_yes": 0.58,
      "15_4_#default#": 0.27
    },
    "paper": {
      "dimensions": {
        "height": 1425,
        "width": 750,
        "x": 840,
        "y": 220
      }
    }
  }
inputs:
- key: file_id
  value:
    complex:
      root: File
      accessor: EntryID
  required: false
  description: File to detonate
- key: Interval
  value:
    simple: "1"
  required: true
  description: Report requests frequency (minutes)
- key: Timeout
  value:
    simple: "60"
  required: true
  description: Report waiting timeout (minutes)
outputs:
- contextPath: File.Name
  description: The full file name (including file extension).
  type: string
- contextPath: File.MD5
  description: The MD5 hash of the file
  type: string
- contextPath: File.SHA1
  description: The SHA1 hash of the file
  type: string
- contextPath: File.SHA256
  description: The SHA256 hash of the file
  type: string
- contextPath: File.Type
  description: File type
  type: string
- contextPath: File.Malicious.Vendor
  description: The vendor that reported the file as malicious
  type: string
- contextPath: File.Malicious.Description
  description: A description explaining why the file was determined to be malicious
  type: string
- contextPath: DBotScore.Indicator
  description: The indicator that was tested
  type: string
- contextPath: DBotScore.Type
  description: The indicator type
  type: string
- contextPath: DBotScore.Vendor
  description: The vendor used to calculate the score
  type: string
- contextPath: DBotScore.Score
  description: The actual score
  type: number
- contextPath: IP.Address
  description: IP address
  type: string
- contextPath: Domain.Name
  description: The Domain name
  type: string
- contextPath: Domain.DNS
  description: A list of IP objects resolved by DNS.
  type: string
- contextPath: URL.Data
  description: The URL
  type: string
- contextPath: RegistryKey.Path
  description: The path to the registry key
  type: string
- contextPath: RegistryKey.Value
  description: The value at the given RegistryKey.
  type: string
- contextPath: Process.Name
  description: Process name
  type: string
- contextPath: Process.PID
  description: Process PID
  type: number
- contextPath: Process.CommandLine
  description: Process Command Line
  type: string
- contextPath: Process.Path
  description: Process path
  type: string
- contextPath: Process.StartTime
  description: Process start time
  type: date
- contextPath: Process.EndTime
  description: Process end time
  type: date
- contextPath: Polygon.Analysis.ID
  description: Analysis ID in TDS
  type: number
- contextPath: Polygon.Analysis.Name
  description: File Name
  type: string
- contextPath: Polygon.Analysis.Size
  description: File Size
  type: number
- contextPath: Polygon.Analysis.Started
  description: Analysis start timestamp
  type: date
- contextPath: Polygon.Analysis.Analyzed
  description: Analysis finish timestamp
  type: date
- contextPath: Polygon.Analysis.MD5
  description: Analyzed file MD5 hash
  type: string
- contextPath: Polygon.Analysis.SHA1
  description: Analyzed file SHA1 hash
  type: string
- contextPath: Polygon.Analysis.SHA256
  description: Analyzed file SHA256
  type: string
- contextPath: Polygon.Analysis.Result
  description: Analysis verdict
  type: string
- contextPath: Polygon.Analysis.Status
  description: The analysis status
  type: string
- contextPath: Polygon.Analysis.Verdict
  description: Analysis verdict
  type: boolean
- contextPath: Polygon.Analysis.Probability
  description: Verdict probability
  type: string
- contextPath: Polygon.Analysis.Families
  description: Malware families
  type: string
- contextPath: Polygon.Analysis.Score
  description: Polygon score
  type: number
- contextPath: Polygon.Analysis.Internet-connection
  description: Internet availability
  type: string
- contextPath: Polygon.Analysis.Type
  description: File type
  type: string
- contextPath: Polygon.Analysis.DumpExists
  description: Network activity dump exists
  type: boolean
- contextPath: Polygon.Analysis.File
  description: The information about files in analysis
  type: unknown
- contextPath: Polygon.Analysis.URL
  description: The information about URL indicators
- contextPath: Polygon.Analysis.IP
  description: The information about IP indicators
- contextPath: Polygon.Analysis.Domain
  description: The information about Domain indicators
- contextPath: Polygon.Analysis.RegistryKey
  description: The information about registry keys which were modified during the
    analysis
- contextPath: Polygon.Analysis.Process
  description: The information about processes started during the analysis
fromversion: 5.0.0
tests:
- No tests
