id: Kenna Test
version: -1
contentitemfields:
  propagationLabels: []
name: Kenna Test
starttaskid: "0"
tasks:
  "0":
    id: "0"
    taskid: 6b55c0b1-4b10-465f-8338-4fd9dffb90bd
    type: start
    task:
      id: 6b55c0b1-4b10-465f-8338-4fd9dffb90bd
      version: -1
      name: ""
      iscommand: false
      brand: ""
    nexttasks:
      '#none#':
      - "1"
    separatecontext: false
    view: |-
      {
        "position": {
          "x": 265,
          "y": 50
        }
      }
    note: false
    timertriggers: []
    ignoreworker: false
    skipunavailable: false
    quietmode: 0
  "1":
    id: "1"
    taskid: a41292d1-3c6b-49ab-82ed-44457ea8d509
    type: regular
    task:
      id: a41292d1-3c6b-49ab-82ed-44457ea8d509
      version: -1
      name: create-ticket
      description: Create a new ticket to the system.
      script: '|||kace-ticket-create'
      type: regular
      iscommand: true
      brand: ""
    nexttasks:
      '#none#':
      - "2"
    scriptarguments:
      asset: {}
      category: {}
      custom_fields: {}
      impact: {}
      machine: {}
      priority: {}
      queue_id:
        simple: "1"
      status: {}
      summary: {}
      title:
        simple: Test number 1
    separatecontext: false
    view: |-
      {
        "position": {
          "x": 265,
          "y": 195
        }
      }
    note: false
    timertriggers: []
    ignoreworker: false
    skipunavailable: false
    quietmode: 0
  "2":
    id: "2"
    taskid: 7cce50ba-13c8-4f9c-8c90-1d6069771d14
    type: regular
    task:
      id: 7cce50ba-13c8-4f9c-8c90-1d6069771d14
      version: -1
      name: tickets list
      description: List of all tickets in the system.
      script: '|||kace-tickets-list'
      type: regular
      iscommand: true
      brand: ""
    nexttasks:
      '#none#':
      - "3"
    scriptarguments:
      custom_shaping: {}
      limit: {}
    separatecontext: false
    view: |-
      {
        "position": {
          "x": 265,
          "y": 370
        }
      }
    note: false
    timertriggers: []
    ignoreworker: false
    skipunavailable: false
    quietmode: 0
  "3":
    id: "3"
    taskid: f61deb0c-4fd0-4cea-80b2-6ae427558582
    type: condition
    task:
      id: f61deb0c-4fd0-4cea-80b2-6ae427558582
      version: -1
      name: validate new ticket
      type: condition
      iscommand: false
      brand: ""
    nexttasks:
      '#default#':
      - "9"
      "yes":
      - "10"
    separatecontext: false
    conditions:
    - label: "yes"
      condition:
      - - operator: isEqualString
          left:
            value:
              complex:
                root: QuestKace
                accessor: Ticket.Title
                transformers:
                - operator: LastArrayElement
            iscontext: true
          right:
            value:
              simple: Test number 1
    view: |-
      {
        "position": {
          "x": 265,
          "y": 545
        }
      }
    note: false
    timertriggers: []
    ignoreworker: false
    skipunavailable: false
    quietmode: 0
  "4":
    id: "4"
    taskid: 7aebed5b-9e83-41e9-84f1-1b151ce923c0
    type: regular
    task:
      id: 7aebed5b-9e83-41e9-84f1-1b151ce923c0
      version: -1
      name: delete ticket
      description: Delete specific ticket by id.
      script: '|||kace-ticket-delete'
      type: regular
      iscommand: true
      brand: ""
    nexttasks:
      '#none#':
      - "8"
    scriptarguments:
      ticket_id:
        complex:
          root: QuestKace
          accessor: Ticket.ID
          transformers:
          - operator: LastArrayElement
    separatecontext: false
    view: |-
      {
        "position": {
          "x": 265,
          "y": 1420
        }
      }
    note: false
    timertriggers: []
    ignoreworker: false
    skipunavailable: false
    quietmode: 0
  "5":
    id: "5"
    taskid: c2f0d048-81ff-46d7-82fb-fb5cb109e0fb
    type: regular
    task:
      id: c2f0d048-81ff-46d7-82fb-fb5cb109e0fb
      version: -1
      name: tickets list
      description: List of all tickets in the system.
      script: '|||kace-tickets-list'
      type: regular
      iscommand: true
      brand: ""
    nexttasks:
      '#none#':
      - "6"
    scriptarguments:
      custom_shaping: {}
      limit: {}
    separatecontext: false
    view: |-
      {
        "position": {
          "x": 265,
          "y": 1770
        }
      }
    note: false
    timertriggers: []
    ignoreworker: false
    skipunavailable: false
    quietmode: 0
  "6":
    id: "6"
    taskid: f8017e6b-40f1-4b17-8418-e34994f85997
    type: condition
    task:
      id: f8017e6b-40f1-4b17-8418-e34994f85997
      version: -1
      name: validate deleted ticket
      type: condition
      iscommand: false
      brand: ""
    nexttasks:
      '#default#':
      - "9"
      "yes":
      - "7"
    separatecontext: false
    conditions:
    - label: "yes"
      condition:
      - - operator: isNotEqualString
          left:
            value:
              complex:
                root: QuestKace
                accessor: Ticket.Title
                transformers:
                - operator: LastArrayElement
            iscontext: true
          right:
            value:
              simple: Test number 1
    view: |-
      {
        "position": {
          "x": 265,
          "y": 1945
        }
      }
    note: false
    timertriggers: []
    ignoreworker: false
    skipunavailable: false
    quietmode: 0
  "7":
    id: "7"
    taskid: bb9768e1-2802-436a-837a-977706277be7
    type: title
    task:
      id: bb9768e1-2802-436a-837a-977706277be7
      version: -1
      name: done
      description: Executes test for all integration instances available and returns
        a detailed table about failed integration instances
      type: title
      iscommand: false
      brand: ""
    separatecontext: false
    view: |-
      {
        "position": {
          "x": 480,
          "y": 2120
        }
      }
    note: false
    timertriggers: []
    ignoreworker: false
    skipunavailable: false
    quietmode: 0
  "8":
    id: "8"
    taskid: 8ef255b1-c1cb-4ca5-84de-6728f362e641
    type: regular
    task:
      id: 8ef255b1-c1cb-4ca5-84de-6728f362e641
      version: -1
      name: delete context
      description: Delete field from context
      scriptName: DeleteContext
      type: regular
      iscommand: false
      brand: ""
    nexttasks:
      '#none#':
      - "5"
    scriptarguments:
      all:
        simple: "yes"
      index: {}
      key: {}
      keysToKeep: {}
      subplaybook: {}
    separatecontext: false
    view: |-
      {
        "position": {
          "x": 265,
          "y": 1595
        }
      }
    note: false
    timertriggers: []
    ignoreworker: false
    skipunavailable: false
    quietmode: 0
  "9":
    id: "9"
    taskid: b3faf854-e28e-47a9-8c1b-f1fa15d47166
    type: title
    task:
      id: b3faf854-e28e-47a9-8c1b-f1fa15d47166
      version: -1
      name: Failed
      type: title
      iscommand: false
      brand: ""
    separatecontext: false
    view: |-
      {
        "position": {
          "x": 50,
          "y": 2120
        }
      }
    note: false
    timertriggers: []
    ignoreworker: false
    skipunavailable: false
    quietmode: 0
  "10":
    id: "10"
    taskid: 0e0aa50e-48c0-4329-8602-c5a42468199b
    type: regular
    task:
      id: 0e0aa50e-48c0-4329-8602-c5a42468199b
      version: -1
      name: update ticket
      description: Update a ticket in the system.
      script: '|||kace-ticket-update'
      type: regular
      iscommand: true
      brand: ""
    nexttasks:
      '#none#':
      - "11"
    scriptarguments:
      asset: {}
      category: {}
      custom_fields: {}
      impact: {}
      machine: {}
      priority: {}
      status: {}
      summary: {}
      ticket_id:
        complex:
          root: QuestKace
          accessor: Ticket.ID
          transformers:
          - operator: LastArrayElement
      title:
        simple: Test number 1 update
    separatecontext: false
    view: |-
      {
        "position": {
          "x": 377.5,
          "y": 720
        }
      }
    note: false
    timertriggers: []
    ignoreworker: false
    skipunavailable: false
    quietmode: 0
  "11":
    id: "11"
    taskid: 2e04b9c4-539e-4446-895f-04d671225e15
    type: regular
    task:
      id: 2e04b9c4-539e-4446-895f-04d671225e15
      version: -1
      name: delete context
      description: Delete field from context
      scriptName: DeleteContext
      type: regular
      iscommand: false
      brand: ""
    nexttasks:
      '#none#':
      - "12"
    scriptarguments:
      all:
        simple: "yes"
      index: {}
      key: {}
      keysToKeep: {}
      subplaybook: {}
    separatecontext: false
    view: |-
      {
        "position": {
          "x": 377.5,
          "y": 895
        }
      }
    note: false
    timertriggers: []
    ignoreworker: false
    skipunavailable: false
    quietmode: 0
  "12":
    id: "12"
    taskid: f0e67e84-141f-4aef-8b6b-01ab5443d381
    type: regular
    task:
      id: f0e67e84-141f-4aef-8b6b-01ab5443d381
      version: -1
      name: tickets list
      description: List of all tickets in the system.
      script: '|||kace-tickets-list'
      type: regular
      iscommand: true
      brand: ""
    nexttasks:
      '#none#':
      - "13"
    scriptarguments:
      custom_shaping: {}
      limit: {}
    separatecontext: false
    view: |-
      {
        "position": {
          "x": 377.5,
          "y": 1070
        }
      }
    note: false
    timertriggers: []
    ignoreworker: false
    skipunavailable: false
    quietmode: 0
  "13":
    id: "13"
    taskid: f48c3930-4b14-496a-8141-5d38d3f798f6
    type: condition
    task:
      id: f48c3930-4b14-496a-8141-5d38d3f798f6
      version: -1
      name: validate update ticket
      type: condition
      iscommand: false
      brand: ""
    nexttasks:
      '#default#':
      - "7"
      "yes":
      - "4"
    separatecontext: false
    conditions:
    - label: "yes"
      condition:
      - - operator: isEqualString
          left:
            value:
              complex:
                root: QuestKace
                accessor: Ticket.Title
                transformers:
                - operator: LastArrayElement
            iscontext: true
          right:
            value:
              simple: Test number 1 update
    view: |-
      {
        "position": {
          "x": 377.5,
          "y": 1245
        }
      }
    note: false
    timertriggers: []
    ignoreworker: false
    skipunavailable: false
    quietmode: 0
view: |-
  {
    "linkLabelsPosition": {},
    "paper": {
      "dimensions": {
        "height": 2135,
        "width": 810,
        "x": 50,
        "y": 50
      }
    }
  }
inputs: []
outputs: []
